name: Update incidents from repo B

on:
  schedule:
    - cron: '0 0 1,15 * *'  # every 1st and 15th day of the month
  workflow_dispatch:

jobs:
  update-incidents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo DeFiHackLabs-Incident-Explorer
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Clone repo DeFiHackLabs
        run: |
          git clone https://github.com/Stamp9/DeFiHackLabs.git main_repo
          cd main_repo
          git fetch
          git rev-parse HEAD > ../repo_main_current_commit.txt

      - name: Parse diff and update incidents
        run: |
          python scripts/parse_diff_and_update.py

            - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          branch="auto/update-incidents-$(date +%Y%m%d%H%M%S)"
          git checkout -b "$branch"

          git add incidents.json .last_repo_main_commit
          git commit -m "Update incidents.json from repo Main diff" || exit 0
          git push origin "$branch"

          gh pr create \
            --title "🤖 Auto Update incidents.json" \
            --body "This PR updates \`incidents.json\` from new events in repo B README." \
            --head "$branch" \
            --base main

